Repository reactphp/filesystem, pull requests merged in 2018-05, with the labels that each got.

#26 Two different exception messages are possible for the same error
  tests/Adapters/FileTest.php
Labels: easy pick, help wanted, maintenance

#14 Test against PHP 7.2
  .travis.yml
Labels: easy pick, maintenance

#15 Refactoring tests
  tests/Adapters/DirectoryTest.php
  tests/Adapters/FileTest.php
  tests/ChildProcess/ProcessTest.php
  tests/Eio/ConstTypeDetectorTest.php
  tests/ModeTypeDetectorTest.php
  tests/Stream/WritableStreamTest.php
Labels: maintenance

#29 No need to run composer self-update, travis does that for us
  travis-init.sh
Labels: easy pick, help wanted, maintenance
