Repository reactphp/filesystem, pull requests merged in 2018-08, with the labels that each got.

#31 Allow PHP 5.4 to fail
  .travis.yml
Labels: easy pick, help wanted, maintenance

#39 Test reading and writing from and to binary files
  src/ChildProcess/Adapter.php
  src/WoolTrait.php
  tests/Adapters/FileTest.php
  tests/Adapters/reactphp-logo.png
Labels: bug, easy pick, maintenance

#42 Add supported adapters static method
  src/AdapterInterface.php
  src/ChildProcess/Adapter.php
  src/Eio/Adapter.php
  src/Filesystem.php
  src/FilesystemInterface.php
  tests/TestCase.php
Labels: easy pick, maintenance, new feature
